name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert ipykernel scipy pint numpy matplotlib pandas open-atmos-jupyter-utils
      - run: sudo apt-get install pandoc inkscape texlive-xetex texlive-fonts-recommended
      - uses: actions/checkout@v2
      - run: |
          for file in $(find lab* -type f -name "*.ipynb"); do
            python -m nbconvert --to pdf --execute "$file"
          done
      - uses: actions/upload-artifact@v4
        with:
          path: lab*/*.pdf
