name: Generate pdf for changed notebooks
run-name: ${{ github.actor }} triggered workflow ${{ github.workflow }} from branch ${{ github.ref }}
on:
  push:
    paths:
      - 'lab*/**.ipynb'
  workflow_dispatch:

jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install uv

      - run: uv sync

      - run: sudo apt-get update

      - run: sudo apt-get install pandoc inkscape texlive-xetex texlive-fonts-recommended

      - run: |
          for file in $(find lab* -type f -name "*.ipynb"); do
            uv tool run --from nbconvert --to pdf --execute "$file"
          done

      - uses: actions/upload-artifact@v4
        with:
          path: lab*/*.pdf
